/**
 * --- SIMULATION CONFIGURATION ---
 */
export const SIMULATION_DAYS = 30
export const STUDENT_COUNT = 30
export const PRACTICE_PER_SESSION = 6
export const SESSION_PROBABILITY = 0.55

export const XP_MAP = {
  CONTENT_READ: 10,
  SOCRATIC_HINT_USED: 5,
  PRACTICE_CORRECT: 15,
  PRACTICE_INCORRECT: 2,
  CHECKPOINT_PASS: 100,
  CHECKPOINT_FAIL: 20,
  EXAM_PASS: 500,
  EXAM_FAIL: 50
}
